"""Tests for DocumentManagerWorkflow.

Generated by Workflow Factory.
Expanded with comprehensive test coverage.

Copyright 2025 Smart-AI-Memory
Licensed under Fair Source License 0.9
"""

import pytest
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

from empathy_os.workflows.document_manager import DocumentManagerWorkflow
from empathy_os.workflows.base import ModelTier


class TestDocumentManagerWorkflow:
    """Test suite for DocumentManagerWorkflow."""

    @pytest.fixture
    def workflow(self):
        """Create workflow instance for testing."""
        return DocumentManagerWorkflow()

    @pytest.mark.asyncio
    async def test_workflow_initialization(self, workflow):
        """Test workflow initializes correctly."""
        assert workflow.name == "document-manager"
        assert (
            workflow.description
            == "You are an expert in the creating wide many types of documents. You use program libraries, systems, style guide, and industry best practices, to efficiently create and update documentation for the empathy-framework."
        )
        assert workflow.stages == ["process"]

    @pytest.mark.asyncio
    async def test_workflow_tier_map(self, workflow):
        """Test tier mapping is correct."""
        assert workflow.tier_map["process"] == ModelTier.CAPABLE

    def test_scan_codebase_nonexistent_path(self, workflow):
        """Test _scan_codebase with non-existent path."""
        result = workflow._scan_codebase(Path("/nonexistent/path"))
        assert "Path does not exist" in result

    def test_scan_codebase_file(self, workflow, tmp_path):
        """Test _scan_codebase with a single file."""
        test_file = tmp_path / "test.py"
        test_file.write_text("# Test content\nprint('hello')")

        result = workflow._scan_codebase(test_file)

        assert "File: test.py" in result
        assert "Test content" in result

    def test_scan_codebase_directory(self, workflow, tmp_path):
        """Test _scan_codebase with a directory."""
        # Create directory structure
        (tmp_path / "src").mkdir()
        (tmp_path / "src" / "module.py").write_text('"""Module docstring."""\nclass Foo: pass')
        (tmp_path / "README.md").write_text("# Test Project\nThis is a test.")
        (tmp_path / "pyproject.toml").write_text('[project]\nname = "test"')

        result = workflow._scan_codebase(tmp_path)

        assert "README.md" in result
        assert "pyproject.toml" in result
        assert "Directory Structure" in result

    def test_scan_codebase_extracts_docstrings(self, workflow, tmp_path):
        """Test _scan_codebase extracts docstrings from Python files."""
        src_dir = tmp_path / "src"
        src_dir.mkdir()
        py_file = src_dir / "example.py"
        py_file.write_text('"""This is a module docstring for testing."""\n\ndef func(): pass')

        result = workflow._scan_codebase(tmp_path)

        assert "This is a module docstring" in result

    @pytest.mark.asyncio
    async def test_run_stage_unknown_stage(self, workflow):
        """Test run_stage raises ValueError for unknown stage."""
        with pytest.raises(ValueError, match="Unknown stage"):
            await workflow.run_stage("unknown_stage", ModelTier.CAPABLE, {})

    @pytest.mark.asyncio
    async def test_run_stage_process(self, workflow):
        """Test run_stage with 'process' stage."""
        with patch.object(workflow, "_process", new_callable=AsyncMock) as mock_process:
            mock_process.return_value = ("result", 100, 50)

            result = await workflow.run_stage("process", ModelTier.CAPABLE, {"path": "."})

            mock_process.assert_called_once_with({"path": "."}, ModelTier.CAPABLE)
            assert result == ("result", 100, 50)

    @pytest.mark.asyncio
    async def test_process_with_mock_llm(self, workflow, tmp_path):
        """Test _process method with mocked LLM call."""
        # Create a simple test directory
        (tmp_path / "README.md").write_text("# Test")

        with patch.object(workflow, "_call_llm", new_callable=AsyncMock) as mock_llm:
            mock_llm.return_value = ("Generated documentation", 500, 200)

            result, input_tokens, output_tokens = await workflow._process(
                {"path": str(tmp_path)}, ModelTier.CAPABLE
            )

            assert result == "Generated documentation"
            assert input_tokens == 500
            assert output_tokens == 200
            mock_llm.assert_called_once()

    @pytest.mark.asyncio
    async def test_process_default_path(self, workflow):
        """Test _process uses default path when not specified."""
        with patch.object(workflow, "_call_llm", new_callable=AsyncMock) as mock_llm:
            mock_llm.return_value = ("Doc", 100, 50)

            await workflow._process({}, ModelTier.CAPABLE)

            # Verify it was called (path defaults to ".")
            mock_llm.assert_called_once()

    @pytest.mark.asyncio
    async def test_process_with_string_input(self, workflow):
        """Test _process handles non-dict input gracefully."""
        with patch.object(workflow, "_call_llm", new_callable=AsyncMock) as mock_llm:
            mock_llm.return_value = ("Doc", 100, 50)

            # String input should use default path "."
            await workflow._process("some string", ModelTier.CAPABLE)

            mock_llm.assert_called_once()

    def test_scan_codebase_handles_read_error(self, workflow, tmp_path):
        """Test _scan_codebase handles file read errors gracefully."""
        test_file = tmp_path / "unreadable.py"
        test_file.write_text("content")
        test_file.chmod(0o000)  # Remove read permissions

        try:
            result = workflow._scan_codebase(test_file)
            # Should either return error message or handle gracefully
            assert result is not None
        finally:
            test_file.chmod(0o644)  # Restore permissions for cleanup

    def test_scan_codebase_limits_file_count(self, workflow, tmp_path):
        """Test _scan_codebase limits number of files scanned."""
        src_dir = tmp_path / "src"
        src_dir.mkdir()

        # Create more than 10 Python files
        for i in range(15):
            (src_dir / f"module_{i}.py").write_text(f'"""Module {i}"""')

        result = workflow._scan_codebase(tmp_path)

        # Should only show up to 10 files
        module_count = result.count("module_")
        assert module_count <= 10
