"""Tests for ManageDocsWorkflow.

Generated by Workflow Factory.
Expanded with comprehensive test coverage.

Copyright 2025 Smart-AI-Memory
Licensed under Fair Source License 0.9
"""

import pytest
from unittest.mock import AsyncMock, MagicMock, patch

from empathy_os.workflows.manage_docs import ManageDocsWorkflow
from empathy_os.workflows.base import ModelTier


class TestManageDocsWorkflow:
    """Test suite for ManageDocsWorkflow."""

    @pytest.fixture
    def workflow(self):
        """Create workflow instance for testing."""
        return ManageDocsWorkflow()

    @pytest.mark.asyncio
    async def test_workflow_initialization(self, workflow):
        """Test workflow initializes correctly."""
        assert workflow.name == "manage-docs"
        assert workflow.description == "Manage documentation"
        assert workflow.stages == ["process"]

    @pytest.mark.asyncio
    async def test_workflow_tier_map(self, workflow):
        """Test tier mapping is correct."""
        assert workflow.tier_map["process"] == ModelTier.CAPABLE

    @pytest.mark.asyncio
    async def test_run_stage_unknown_stage(self, workflow):
        """Test run_stage raises ValueError for unknown stage."""
        with pytest.raises(ValueError, match="Unknown stage"):
            await workflow.run_stage("invalid_stage", ModelTier.CAPABLE, {})

    @pytest.mark.asyncio
    async def test_run_stage_process(self, workflow):
        """Test run_stage with 'process' stage."""
        with patch.object(workflow, "_process", new_callable=AsyncMock) as mock_process:
            mock_process.return_value = ({"result": "test"}, 100, 50)

            result = await workflow.run_stage("process", ModelTier.CAPABLE, {"data": "test"})

            mock_process.assert_called_once_with({"data": "test"}, ModelTier.CAPABLE)
            assert result == ({"result": "test"}, 100, 50)

    @pytest.mark.asyncio
    async def test_process_with_executor(self, workflow):
        """Test _process method when executor is available."""
        mock_executor = MagicMock()
        mock_result = MagicMock()
        mock_result.content = {"processed": True}
        mock_result.input_tokens = 200
        mock_result.output_tokens = 100
        mock_executor.run = AsyncMock(return_value=mock_result)

        workflow._executor = mock_executor

        result, in_tokens, out_tokens = await workflow._process(
            {"task": "generate docs"}, ModelTier.CAPABLE
        )

        assert result == {"processed": True}
        assert in_tokens == 200
        assert out_tokens == 100
        mock_executor.run.assert_called_once()

    @pytest.mark.asyncio
    async def test_process_fallback_no_executor(self, workflow):
        """Test _process method falls back when no executor."""
        workflow._executor = None

        result, in_tokens, out_tokens = await workflow._process(
            {"task": "test"}, ModelTier.CAPABLE
        )

        assert result["result"] == "Processed"
        assert result["input"] == {"task": "test"}
        assert in_tokens == 0
        assert out_tokens == 0

    @pytest.mark.asyncio
    async def test_process_with_string_input(self, workflow):
        """Test _process handles string input."""
        workflow._executor = None

        result, in_tokens, out_tokens = await workflow._process(
            "string input", ModelTier.CAPABLE
        )

        assert result["result"] == "Processed"
        assert result["input"] == "string input"

    @pytest.mark.asyncio
    async def test_process_with_list_input(self, workflow):
        """Test _process handles list input."""
        workflow._executor = None

        result, in_tokens, out_tokens = await workflow._process(
            ["item1", "item2"], ModelTier.CAPABLE
        )

        assert result["result"] == "Processed"
        assert result["input"] == ["item1", "item2"]

    @pytest.mark.asyncio
    async def test_workflow_stages_list(self, workflow):
        """Test workflow has expected stages."""
        assert len(workflow.stages) == 1
        assert "process" in workflow.stages

    @pytest.mark.asyncio
    async def test_workflow_tier_is_capable(self, workflow):
        """Test default tier is CAPABLE for docs workflow."""
        tier = workflow.tier_map.get("process")
        assert tier == ModelTier.CAPABLE
        assert tier.value == "capable"

    @pytest.mark.asyncio
    async def test_process_prompt_contains_input(self, workflow):
        """Test _process creates prompt containing input data."""
        mock_executor = MagicMock()
        mock_result = MagicMock()
        mock_result.content = "result"
        mock_result.input_tokens = 50
        mock_result.output_tokens = 25
        mock_executor.run = AsyncMock(return_value=mock_result)

        workflow._executor = mock_executor

        await workflow._process({"key": "value"}, ModelTier.CAPABLE)

        # Verify run was called with prompt containing input
        call_args = mock_executor.run.call_args
        assert "key" in str(call_args) or "value" in str(call_args)

    def test_workflow_inheritance(self, workflow):
        """Test workflow inherits from BaseWorkflow."""
        from empathy_os.workflows.base import BaseWorkflow

        assert isinstance(workflow, BaseWorkflow)

    def test_workflow_has_model_tier_reference(self, workflow):
        """Test workflow has ModelTier reference."""
        # Access via the workflow
        assert hasattr(workflow, "tier_map")
        assert all(
            isinstance(tier, ModelTier) for tier in workflow.tier_map.values()
        )
